version: '3.8'

services:
  zookeeper:
#    platform: linux/amd64
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
#    platform: linux/amd64
    image: bitnami/kafka:3.3.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes

      # High-throughput performance tuning
      - KAFKA_CFG_NUM_NETWORK_THREADS=8
      - KAFKA_CFG_NUM_IO_THREADS=16
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=104857600
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760

      # Default topic retention policy
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
    volumes:
      - kafka_data:/bitnami/kafka
    depends_on:
      - zookeeper

  kadeck:
#    platform: linux/amd64
    image: xeotek/kadeck
    container_name: kadeck
    ports:
      - "9999:8133"
    environment:
      - xeotek_kadeck_free=dccunning@gmail.com
      - xeotek_kadeck_secret=fgaJDS9348asdjsbdDIB472923u
    depends_on:
      - kafka


volumes:
  kafka_data: